import * as THREE from 'three';
export default {
	iTime: { value: 1 },
	//Planet uniforms
	_PSNoiseOffset: {value: new THREE.Vector3(10.62, 0, 0)},
	_PSNoiseGlobalScale: {value: 1},
	_PSWaterHeight: {value: 0.7},
	_PSWaterDepthOffset: {value: 0.3},
	_PSMaxHeightOffset: {value: 0.1},
	_PlanetColor1: {value: new THREE.Color(0,0.4,0.3)},
	_PlanetColor2: {value: new THREE.Color(0.2,1,0.8)},
	_PlanetHighInterpRange: {value: new THREE.Vector2(0.0, 1.0)},

	_PSNoiseScales: {value: new THREE.Vector2(2,20)}, 
	_SecondaryNoiseStrengthGround: {value: 0.07},
	_MaxScrewTerrain: {value: 0},
	_PSDensityOffset: {value: 0},
	_SurfaceMinLight: {value: 0.2},
	_PlanetSurfaceWaterStepSize: {value: 0.005},
	_PlanetSurfaceWaterMaxStepCount: {value: 100},
	_GridHalfSize: {value: 30.0},
	_VoxelNormalInterp: {value: 1.0},
	_EnableVoxelizer: {value: false},
	//Ocean uniforms
	_showWater: {value: true},
	_WaterColorDepth: {value: new THREE.Color(0.1,0.1,0.3)},
	_WaterColor: {value: new THREE.Color(0.6,0.8,1)},
	_WaterSpecularColor: {value: new THREE.Color(1.0,1.0,1.0)},
	_WaterMaterialSmoothStep: {value: new THREE.Vector2(4.92, 0)},
	_WaterNormalScale: {value: 12.46},
	_WaterSurfaceMinLight: {value: 0.44},
	_WaterNormalStrength: {value: 0.5},
	_SpecularParams: {value: new THREE.Vector2(3.4, 0.33)},
	_WaterMoveSpeed: {value: 0.2},
	//Cloud uniforms
	_CloudTransparency: {value: 1},
	_CloudColor1: {value: new THREE.Color(0, 0.5, 0.8)},
	_CloudColor2: {value: new THREE.Color(1, 1, 1)},
	_MaxScrewCloud: {value: 0.6},
	_BreakDistanceCloud: {value: 1.1},
	_CloudMidDistance: {value: 0.8},
	_CloudHalfHeight: {value: 0.053},
	_CloudNoiseScales: {value: new THREE.Vector2(3, 30)},
	_CloudNoiseOffset: {value: new THREE.Vector3(0,0,0)},
	_CloudNoiseGlobalScale: {value: 1.07},
	_SecondaryNoiseStrength: {value: 0.1},
	_CloudDensityMultiplier: {value: 1.14},
	_CloudDensityOffset: {value: -0.1},
	_CloudMoveSpeed: {value: 0.1},
	_CloudsStepSize: {value: 0.01},
	_CloudsMaxStepCount: {value: 100},
	_CloudsPosterize: {value: true},
	_CloudsPosterizeCount: {value: 4},
	//Ambient
	_AmbientColor: {value: new THREE.Color(0.1,0.1,0.3)},
	_AmbientPower: {value: 4.0},
	//Misc
	_CylinderHeight: {value: 5.0},
	_CylinderRad: {value: 2.88}
};